# Nome da aplicação
spring.application.name=Gestao_Notas

# Configurações do Banco de Dados em Produção (ex: PostgreSQL / MySQL)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestao_notas_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logs
logging.level.root=WARN
logging.level.br.com.gos.devshowcase=INFO

# Servidor
server.port=${PORT:8080}
springdoc.swagger-ui.path/swagger-ui.html
